#!/bin/bash

# Watch all *.go files in the specified directory
# Call the restart function when they are saved
function monitor() {
  inotifywait -q -m -r -e modify --exclude '[^g][^o]$' /app/src |
  while read line; do
    restart
  done
}

# Terminate and rerun the main Go program
function restart {
  if [ "$(pidof $PROCESS_NAME)" ]; then
    killall -q -w -9 $PROCESS_NAME
    killall -q -w -9 go-reload
  fi
  echo ">> Reloading..."
  eval "gb build -R="/app" -ldflags="-extldflags=-ldl" all"
  
  eval "/app/bin/$PROCESS_NAME $ARGS &"
}

# Make sure all background processes get terminated
function close {
  killall -q -w -9 inotifywait
  exit 0
}

trap close INT
echo "== Go-reload"
echo ">> Watching directories, CTRL+C to stop"

FILE_PATH=$1
FILE_NAME=$(basename $FILE_PATH)
PROCESS_NAME=$1

ARGS=$@

# Start the main Go program
gb build -R="/app" -ldflags="-extldflags=-ldl" all

/app/bin/$PROCESS_NAME $ARGS &

monitor /app/src

wait

